[profile.default]
libs = ["lib"]
out = "out"
src = "src"
via-ir = true

optimizer = true
optimizer_runs = 200
remapping = [
    "@openzeppelin-upgrades=lib/eigenlayer-middleware/lib/openzeppelin-contracts-upgradeable",
    "@openzeppelin=lib/eigenlayer-middleware/lib/openzeppelin-contracts",
]
solc = '0.8.28'
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
mainnet = {key = "${ETHERSCAN_API_KEY}"}
optimism = {key = "${ETHERSCAN_OPTIMISM_KEY}"}
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
op-sepolia = "${OP_SEPOLIA_RPC_URL}"
optimism = "${OP_MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
